### ISSUE TITLE
KeyboardRespondable first responder check improvements

### ISSUE THREAD

**Issue by ganttastic** [BottleRocketStudios/iOS-KeyboardSupport#45]
I recently ran into an issue with KeyboardRespondable. I needed the table view to adjust it's scroll insets based on the keyboard, so I conformed to the protocol in my view controller and added the proper setup code but it wasn't adjusting.

It looks like there is a check for `activeFirstResponder()` by iterating through its view controller's subviews. My problem is the active first responder is actually inside the navigation bar outside of it's hierarchy.

Working around this can be difficult as the check is an extension on UIView with no opportunity to inject myself into its decision making process.

I'd like to propose either removing this check (as I don't see the benefit, but please let me know if I'm missing something) or at least adding a way for conformers to override this. Let me know if you have any questions.

**Comment by tylermilner** [comment]
@ganttastic Could you provide a sample project (or rather setup an example inside of the sample project)?

Most likely we'll need to keep the check for the `activeFirstResponder()` since we use it to determine which text field to auto-scroll to in [KeyboardScrollable.swift](https://github.com/BottleRocketStudios/iOS-KeyboardSupport/blob/master/Sources/KeyboardSupport/KeyboardScrollable.swift#L110).

You might be able to get away with just conforming to `KeyboardDismissable` if you don't need the auto-scroll behavior. Otherwise, we'll probably just need the stuff in `KeyboardScrollable` to make use of some sort of `FirstResponderProviding` protocol that you could override when necessary.

**Comment by ganttastic** [comment]
@tylermilner I found that `KeyboardSafeAreaAdjustable` met my needs. Closing this issue.
